version: '3.9'

services:
  flask-app:
    image: flask-app1
    build:
      context: .
    ports:
      - "5000:5000"
    # Define el volumen aquí para la conexión a Docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
